### PR TITLE
My New Scripts

### PR DESCRIPTION
**Pull request by PKMWM1**
I have been making scripts ever since the feature was added and have been wanting to contribute what I have created so others can use them as well. So I added all of the new scripts and data. More details about what has been added are compiled within a README text which is within the src folder but will also be attached here. I have tested almost all of them, but backups are still recommended.
[README.txt](https://github.com/FlagBrew/PKSM-Scripts/files/2592443/README.txt)

### CODE REVIEW

**Comment by SpiredMoth** [comment]
I'll give this a more thorough look over the coming days.

I do already have a few comments:
- `all games` **Item x65535** - I'm very hesitant to add these due to the very reason you pointed out: `It will render in game as ?35`. It's not a stretch to believe that some users would not read the documentation, see the odd display in-game, and blame it on PKSM and/or the script. Plus there's no legitimate way to get that many in-game at once. I might add some under "illegal," but definitely not all of them.
- `ORAS, XY` **All S and MAX O-Powers** - You could have made use of the `rpt` value instead of listing each power's offset separately. Also, I believe this is essentially the same as the **Unlock all O-Powers (illegal)** scripts I added not too long ago.
- `ORAS, XY` **Supreme Honor Pokepuffs** - Again, could have used the `rpt` value rather than listing all the offsets separately
- `USUM` **All Pokebeans** - could have used `rpt`
- `B2W2` **Items slot 1 - Relic Crown x65535** - you have this one in the file twice
- `B2W2` **Join Avenue - Import** - I'm probably going to leave this out since users will probably want to customize what shops they inject

**Comment by PKMWM1** [comment]
Thank you for your feedback. A lot of these scripts I made several months ago before I knew how to use the more intricate features such as repeating values and .bin files. For example, the All S and MAX Powers I made over the summer before yours was added. The Join Avenue script was mainly for myself but thought it might be useful to someone in case someone wanted to make their own. I can probably clean the repeating ones up if that is necessary

**Comment by SpiredMoth** [comment]
I've taken another look through this and have a few more notes/comments/questions:

- `all games` **item x999** -- With the existing item scripts these feel unnecessary, *especially* with PKSM v5 not having subdirectory support
    - The money items (Nugget, Relic Crown, etc.) in particular feel unnecessary given the existing scripts for **Max money** and items. Honestly, how often do you see someone blowing through the funds from max money + selling off extra items from existing item scripts between PKSM sessions?
- `all games` **item/slot x65535** -- I'm going to err on the side of caution and not include these. Also see the reason for **item x999** above
    - `BW, B2W2` **Items slot 1 - Pass Orb x65535** - I *will* include this due to the MAX powers requiring the greater quantity, but will label it "illegal" or probably combine it with the MAX powers scripts
- `BW, B2W2` **People passed** - I take it from the comment in your readme that these don't affect a game mechanic?
- `BW, B2W2` **Reset Geonet** - afaik last 2 targeted offsets are checksum related. Did you find that setting them with the script was necessary for it to work right?
- `B2W2` **Reset N and Shadow Triad** - Why are these combined together? consecutive battles? share an offset? convenience?
- `DP, Pt` **Set 49 Underground Flags** - does this actually lead to Platinum Flag after obtaining 1 more?
- `HGSS` **Reset Sinjoh Ruins**
    - Was this tested with an event Arceus? Hall of Origin Arceus?
    - Does it reset chosen trio member?
- `SM, USUM` **All Pokebeans** - when you changed these to use a repeat value, you repeated the script name which causes compile problems


I still have testing and research I need to do on some of your scripts which I will be doing over time. Feel free to make whatever edits you want, but I'll probably make a brand new commit of my own with what I feel is worth adding and credit you for it.

**Comment by PKMWM1** [comment]
Here is my response to your comments 

With the Items: It’s up to you. I use them for my own purposes, because sometimes you just want a small cash injection without setting it to max

With x65535: like before it’s your call, but I think you should keep at least x65535 for slot 1 of the various bags and put it under illegal scripts so it can be the individual user’s choice whether or not they wish to use them. I just want the option to be there.

People Passed: These codes were just to satisfy a personal pet peeve of the game counting every single time my games communicated with each other

Reset Geonet: I don’t really know. I just made that code because you can’t change it in game and if I moved, I didn’t want my location to be off without having to reset the whole game. It worked for me so I didn’t put much thought into it.

Reset N and Shadow Triad: These scripts are together because they are the two battles you can only do once a season and I didn’t like having to change the clock or wait a whole month for a rematch. The primary reason they are together is for convenience sake. Perhaps it should be renamed to something like “Reset Seasonal Battles” but I thought most people wouldn’t know exactly which battles they refer to. I’d like to add the option for the first Cynthia battle in there. But I need to replay the game in order to find the offset

Set 49 Flags: Yes, in my experience, acquiring one more will turn your flag platinum. Although I tested it when I already had a Gold Flag. I also felt that 9999999 or whatever flags just didn’t look good.

Reset Sinjoh Ruins: Tested with both types of Arceus and yes. The script COMPLETELY resets the whole event. So you can complete both events, run the script and do it again. Yes, this resets the chosen Pokemon as well. It is also safe to use it in between the events but I wouldn’t use it when the event is already in progress 

Reset Pokebeans: I replaced the old code with the updated code and had no trouble compiling. Did you erase the original from your list?

I have also have to ask wether or not these scripts will be compatible with the new PKSM as I am afraid that the new rewrite will break all of my scripts. I asked on Discord a couple of weeks ago and was told that they would still work under “Legacy Scripts” or something. 

p.s: I also made codes to alter the Experience received by Pokemon in the day-care for all Gen 4, 5, and 6 games. For example, one of them will add 1,000,000 exp to both Pokémon in the day-care. The reason for this is that especially in Gen 4, it can take a while to give 50+ rare candies to one Pokémon to get it leveled up. Should I add these as well?

**Comment by SpiredMoth** [comment]
I made a local clone after you made the changes and used genScripts.py to make all the new ones at once and encountered the errors in your Pokebeans scripts
https://github.com/FlagBrew/PKSM-Scripts/blob/5d6841002bcbe34f6b886316d553583b6c000de8/src/scriptsSM.txt#L96
https://github.com/FlagBrew/PKSM-Scripts/blob/5d6841002bcbe34f6b886316d553583b6c000de8/src/scriptsUSUM.txt#L151
Hopefully you now see what I mean by repeating the script name

All existing scripts, including the ones in this PR, will be compatible with the rewrite (PKSMv6). "Legacy" just refers to non-picoC scripts.

You're welcome to add whatever scripts you want to this PR. I'll eventually see to it that everything that needs it gets tested.

**Comment by SpiredMoth** [comment]
I merged in all your scripts that I felt deserved to be added in 8086bd9, although I didn't test many of them so I haven't confirmed for myself whether they all work

There were a few scripts I thought would be good additions (such as the DPPt Honey Tree ones), but combined as picoC scripts rather than these individual simple versions.

**Pull request closed without merging**
