### PR TITLE
Fixed genScript.py crashing

### PR DESCRIPTION
**Pull request by PlasticJustice**
genScript.py no longer crashes if one (or more) of the scriptGAME.txt files are missing.

### CODE REVIEW

**Comment by SpiredMoth** [comment]
Maybe I'm missing something by not being familiar with Python but why did you remove `shutil.rmtree("scripts", True)` and perform the file replacement manually?

**Comment by PlasticJustice** [comment]
By deleting the folder you lose all the scripts, which isn't a big deal if they're going to be made again. But if you have scripts in the folder that aren't included in the /src/scripts.txt, they won't be deleted, the other scripts will just added.

Ex: Folder contains a.pksm and c.pksm. scripts.txt is going to make b.pksm and c.pksm.
b.pksm will be added, c.pksm will be replaced, and a.pksm will remain there

**Comment by SpiredMoth** [comment]
Guess that's more of a personal workflow style (I keep all my development stuff in a different, uncommitted directory)

Maybe this is just my JS experience and unfamiliarity with Python but looking over the code again it also seems that you're unnecessarily repeating some code, like the `for game in games` loop, because of the way you constructed a couple of your conditionals

**Comment by piepie62** [comment]
The way that I designed it, genScripts was meant for basically only production. Anything other than full production compilation should probably be manually copied, anyway

**Comment by piepie62** [comment]
Furthermore, the scriptGAME.txt files should NEVER be deleted, instead use PKSMScript directly

**Comment by SpiredMoth** [comment]
What exactly do the WC renewal scripts do? At this point they're the only reason I'm keeping this open, and I'm thinking of including them when I deal with #2

**Comment by BernardoGiordano** [comment]
@SpiredMoth they probably set the `redeemed` flag to false so that you can get them another time from the postman. I'd say it would be good to generalize them in a C script rather then hardcoding them and having up to 48 scripts to do the same thing with different offsets

**Comment by SpiredMoth** [comment]
@PlasticJustice check out `/dev/python/genScriptsDev.py` -- I'm pretty sure I covered all the functionality you were going for

Also added the WC renewal scripts in 8086bd9 so this can be closed

**Pull request closed without merging**
